group/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import EntityLookupView, EntityDetailView, EntityUpdateView

urlpatterns = [
    path('group/<int:id>/<slug:slug>/', EntityDetailView.as_view(), name="entity_detail_view"),
    url(r'^lookup/$', EntityLookupView.as_view(), name="entity_lookup_view"),
    path('group/<int:id>/<slug:slug>/update/', EntityUpdateView.as_view(), name='entity_update_view')
]

grouper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('user_auth.urls')),
    url(r'^', include('group.urls')),
    url(r'^', include('alerts.urls')),
    url(r'^', include('events.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from group.models import Entity
from django.utils import timezone
from datetime import timedelta

class Event(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    entity = models.ForeignKey(Entity,on_delete=models.CASCADE)
    time = models.DateTimeField()
    description = models.TextField()
    urgent = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)

    @property
    def is_expired(self):
        if self.time < timezone.now() + timedelta(hours=1):
            return True
        return False

templates/landing_leader.html
{% extends 'leader_base.html' %}

{% block content %}



{% for e in request.user.userentityrelation_set.all %}



  <div class="row">
    <div class="col-md-6">
      <h2 style="text-align:center;">{{ e.entity.name }}</h2>
      {% if request.user.get_alerts %}
        <h4>Active Alerts</h4>
        {% for alert in request.user.get_alerts %}
          <span>Alert:</span>{{ alert.headline }} <span>Expiration:</span>{{ alert.expiration_time }}
        {% endfor %}
      {% endif %}

      <div class="row">
        <div class="col-md-4">
          <a href="{% url 'entity_update_view' e.entity.id e.entity.slug %}">Update Info</a>
        </div>
        <div class="col-md-4">
          <a href="{% url 'event_create_view' e.entity.slug %}">Create Event</a>
        </div>
        <div class="col-md-4">
          <a href="{% url 'alert_create_view' e.entity.slug %}">Create Alert</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h3 style="text-align:center;">Upcoming Events</h3>
      {% for event in e.entity.event_set.all %}
        {% if not event.is_expired %}
          <div class="row eventrow">
            <div class="col-md-6">
              <span>{{ event.name }}</span><br>
              <span>{{ event.location }}</span><br>
              <span>{{ event.time }}</span>
            </div>
            <div class="col-md-6">
              <span>{{ event.description|linebreaks }}</span>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>


{% endfor %}

{% endblock %}

templates/landing_member.html
{% extends 'member_base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if request.user.get_alerts %}
    {% for alert in request.user.get_alerts %}

    <div class="alert-box">
      <h3>{{ alert.headline }}</h3>
      <p>{{ alert.text }}</p>
    </div>

    {% endfor %}
    {% endif %}
  </div>
</div> <!-- end alert row -->

<div class="row">
  <div class="col-md-3">
    <h3>Search Groups</h3>
    <div class="group-search">
      <span>Enter group code:</span>
      <form class="" action="/lookup/" method="post">
        <input class="groupsearchform" type="text" name="code" value="">
        {% csrf_token %}
        <input class="btn btn-primary searchbtn" type="submit" name="" value="GO">
      </form>
    </div>
    <div class="search-sub-divider"></div>
    <div class="subscriptions-box">
      <h3>Subscriptions</h3>
      {% for e in request.user.userentityrelation_set.all %}
      <div class="group-box">
        <a href="{% url 'entity_detail_view' e.entity.id e.entity.slug %}">{{ e.entity.name }}</a>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="col-md-9">
    <h3 style="text-align:center;">Upcoming Events</h3>
    {% for event in request.user.get_events %}
    {% if not event.is_expired %}
    <!-- <div class="event-box">
      <div class="row">
        <div class="col-md-3">{{ event.entity.name }}</div>
        <div class="col-md-3">{{ event.name }}</div>
        <div class="col-md-3">{{ event.location }}</div>
        <div class="col-md-3">{{ event.time }}</div>
      </div>
    </div> -->
    <div class="event-box">
      <div class="row">
        <div class="col-md-3">
          <span class="event-name">{{ event.name }} at {{ event.location }}</span><br>
          <span>{{ event.time }}</span>
        </div>
        <div class="col-md-3">
          {{ event.entity }}
        </div>
        <div class="col-md-3">
          <span>Attendance</span>
        </div>
        <div class="col-md-3">
          <span>RSVP</span>
        </div>
      </div>
    </div>

    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/leader_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.js"
      integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA="
      crossorigin="anonymous">
    </script>
    {{ form.media }}
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/leader.css' %}">
    <link rel="stylesheet" href="{% static 'css/leader-forms.css' %}">
  </head>
  <body>
    {% include 'snippets/navbars.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/member_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
  </head>
  <body>
    {% include 'snippets/navbars.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/register_choice_view.html
{% load staticfiles %}
{% load attr_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/userform.css' %}" media="screen">
  </head>
  <body>
    <div class="formblock">
      <div style="height:70px;" class="row spacer"></div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <a href="{% url 'user_create_view' '1' %}"> <button id='userCreateLink' class='btn' type="button">Register to join groups</button> </a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p style="text-align:center;font-size:30px;padding-top:20px;">OR</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <a href="{% url 'user_create_view' '2' %}"> <button id='userCreateLink' class='btn' type="button">Register as group admin</button> </a>
        </div>
      </div>
    </div>

  </body>
</html>